wandb_version: 1

learning_rate:
  desc: null
  value: 0.0001
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: Flags
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1716558488.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.11.9
      5: 0.16.5
      8:
      - 4
      - 5
      13: darwin-arm64
