name: country_from_flag
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - requests
  - beautifulsoup4
  - pytorch::pytorch
  - torchvision=0.18
  - matplotlib
  - opencv
  - scikit-learn